Gnome to basePet
adelfuns/EriaPets pull request #4
Opened 2021-08-17 18:40 UTC by DavidMIXLT

Gnome finished
Added new system for the brain of the gnome

2021-08-17 20:07 UTC, LiveDimensions commented
etselente supongo

2021-08-19 14:52 UTC, adelfuns requested changes

2021-08-19 14:52 UTC, dotdaiya commented on src/main/java/com/virtualeria/eriapets/entities/FlinchPetEntity.java
> +    public void canPoisonTheTarget(Entity target) {
canPoisonTarget

2021-08-19 14:52 UTC, dotdaiya commented on src/main/java/com/virtualeria/eriapets/entities/FlinchPetEntity.java
> +
This line breaks rofl

2021-08-19 14:52 UTC, dotdaiya commented on src/main/java/com/virtualeria/eriapets/entities/ai/task/FollowOwnerTask.java
> +        if (livingEntity == null) {
All of this if else-if statements all return false, i think is better to write it like this

```
boolean notValidLivingEntity = livingEntity == null || livingEntity.isSpectator();
boolean tooFar (or something like that) = mobEntity.squaredDistanceTo(livingEntity) < (double) (this.minDistance * this.minDistance)
if(isValidLivingEntity || mobEntity.isSitting() || tooFar) {
    return false;
}
this.owner = livingEntity;
return true;
```

2021-08-19 14:52 UTC, adelfuns commented on src/main/java/com/virtualeria/eriapets/entities/GnomePetEntity.java
> +    protected void initGoals() {
This one needs to be empty overrided?

2021-08-19 14:52 UTC, dotdaiya commented on src/main/java/com/virtualeria/eriapets/entities/ai/brain/GnomePetBrain.java
> +import net.minecraft.entity.ai.brain.task.*;
We shouldn't use star imports, better single imports

2021-08-19 14:52 UTC, dotdaiya commented on src/main/java/com/virtualeria/eriapets/entities/ai/task/FollowOwnerTask.java
> +        if (mobEntity.getNavigation().isIdle()) {
I think is clearer if this if else if are used with || and the last else delete it since it isn't needed

2021-08-19 14:52 UTC, dotdaiya commented on src/main/java/com/virtualeria/eriapets/entities/ai/task/FollowOwnerTask.java
> +        } else {
Else is not needed if a return in a if is present

2021-08-19 14:52 UTC, dotdaiya commented on src/main/java/com/virtualeria/eriapets/entities/ai/task/FollowOwnerTask.java
> +            } else {
Else is not needed if a return in a if is present

2021-08-19 17:37 UTC, closed without merging